table financials
	lineageTag: 575384ba-f379-4438-bb49-a248888947c2

	/// Total net sales revenue after discounts
	measure 'Total Sales' = SUM(financials[Sales])
		formatString: \$#,0.00
		lineageTag: 93e52e05-2432-4b09-89c0-d39954136780

	/// Total gross sales before discounts
	measure 'Total Gross Sales' = SUM(financials[Gross Sales])
		formatString: \$#,0.00
		lineageTag: eb792d60-b9a2-402c-b3d7-f571af6be4c6

	/// Total discount amount applied
	measure 'Total Discounts' = SUM(financials[Discounts])
		formatString: \$#,0.00
		lineageTag: 43686224-8e06-497c-9986-786cbd208c6e

	/// Total cost of goods sold
	measure 'Total COGS' = SUM(financials[COGS])
		formatString: \$#,0.00
		lineageTag: be0faa68-9cdb-48f2-b4a4-51fd6e5f1ece

		changedProperty = IsHidden

	/// Total net profit
	measure 'Total Profit' = SUM(financials[Profit])
		formatString: \$#,0.00
		lineageTag: fbbe0099-5f20-4213-a407-414073b46bc6

	/// Total quantity of units sold
	measure 'Total Units Sold' = SUM(financials[Units Sold])
		formatString: #,0
		lineageTag: 50308f7f-f0c7-4dd9-bc9b-b240b41a7c26

	/// Profit as a percentage of net sales
	measure 'Profit Margin %' = DIVIDE([Total Profit], [Total Sales])
		formatString: 0.00%
		lineageTag: f46ee06a-b9f8-41bd-a922-30f34606356d

	/// Discount as a percentage of gross sales
	measure 'Discount %' = DIVIDE([Total Discounts], [Total Gross Sales])
		formatString: 0.00%
		lineageTag: 68b0ebe5-5a30-4a02-8f01-de6341824f43

	/// Average net selling price per unit
	measure 'Avg Sale Price' = DIVIDE([Total Sales], [Total Units Sold])
		formatString: \$#,0.00
		lineageTag: 4974a4cb-db5e-4ebc-a5af-1c816ff1150a

	/// Cost of goods sold as a percentage of net sales
	measure 'COGS %' = DIVIDE([Total COGS], [Total Sales])
		formatString: 0.00%
		lineageTag: beeab81c-13a1-471e-a9e7-f9f820456684

	column Segment
		dataType: string
		lineageTag: ec5d1698-253c-4161-9939-6441c90e01cc
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 3d139029-fe31-4d94-a8f5-4b0192a9408f
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 95f27490-e7ec-46d6-adc3-0df9690c3044
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Discount Band'
		dataType: string
		lineageTag: ebe01bd6-1144-47e8-b98b-f436dee09243
		summarizeBy: none
		sourceColumn: Discount Band

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: double
		lineageTag: a99f125a-2b2d-4390-9391-2ff26a478cc9
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Manufacturing Price'
		dataType: int64
		formatString: 0
		lineageTag: 92d799fb-3f3a-46bf-8159-b41aba897f9e
		summarizeBy: sum
		sourceColumn: Manufacturing Price

		annotation SummarizationSetBy = Automatic

	column 'Sale Price'
		dataType: int64
		formatString: 0
		lineageTag: dcc428f7-3b0a-46c9-9e4b-2cfc9213c454
		summarizeBy: sum
		sourceColumn: Sale Price

		annotation SummarizationSetBy = Automatic

	column 'Gross Sales'
		dataType: double
		lineageTag: 271a1397-59c4-42d2-abf4-75b7b789151c
		summarizeBy: sum
		sourceColumn: Gross Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discounts
		dataType: double
		lineageTag: f83e39bb-84ed-498c-9f06-a498c5554c82
		summarizeBy: sum
		sourceColumn: Discounts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sales
		dataType: double
		lineageTag: 06bb34f7-eaef-405f-88a3-7742bf9adc31
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COGS
		dataType: double
		lineageTag: 3efef926-80f7-4e93-9fbd-26fc3b20ef26
		summarizeBy: sum
		sourceColumn: COGS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 4ee23d0a-60f1-4544-87c8-97a09accce05
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 54fef014-a69e-4dbe-ac0e-02a773a35fcc
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 3a8487dd-f130-49f9-aa40-f6237034e05b
			defaultHierarchy: LocalDateTable_2debc536-0034-43d8-a282-8ef82de7208f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 06b2bcdd-03ce-48ae-91ab-c26055df5ccb
		summarizeBy: sum
		sourceColumn: Month Number

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: efa8b4f3-8f3b-4b32-8177-77460226a624
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 7becb9b8-9f10-4195-a6d0-ac1006905957
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	partition financials = m
		mode: import
		source =
				let
				 Source = Excel.Workbook(File.Contents("D:\Program Files\Microsoft Power BI Desktop\bin\SampleData\Financial Sample.xlsx"), null, true),
				    financials_Table = Source{[Item="financials",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(financials_Table,{{"Segment", type text}, {"Country", type text}, {"Product", type text}, {"Discount Band", type text}, {"Units Sold", type number}, {"Manufacturing Price", Int64.Type}, {"Sale Price", Int64.Type}, {"Gross Sales", type number}, {"Discounts", type number}, {"Sales", type number}, {"COGS", type number}, {"Profit", type number}, {"Date", type date}, {"Month Number", Int64.Type}, {"Month Name", type text}, {"Year", Int64.Type}})
				in
				 #"Changed Type"

	annotation PBI_ResultType = Table

